version: '3.8'

services:
  db:
    build:
      context: ./postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  springboot-app:
    build:
      context: ./your-springboot-app
    container_name: springboot-tomcat
    depends_on:
      - db
    ports:
      - "8080:8080"